/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAutocomplete: typeof import('./src/@core/components/forms/AppAutocomplete.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppOtpField: typeof import('./src/@core/components/forms/AppOtpField.vue')['default']
    AppPasswordField: typeof import('./src/@core/components/forms/AppPasswordField.vue')['default']
    AppPhoneNumber: typeof import('./src/@core/components/forms/AppPhoneNumber.vue')['default']
    AppPinField: typeof import('./src/@core/components/forms/AppPinField.vue')['default']
    AppTextField: typeof import('./src/@core/components/forms/AppTextField.vue')['default']
    ButtonLoader: typeof import('./src/@core/components/ButtonLoader.vue')['default']
    ButtonPrimary: typeof import('./src/@core/components/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./src/@core/components/ButtonSecondary.vue')['default']
    CardComponent: typeof import('./src/components/card/CardComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageSpinLoader: typeof import('./src/@core/components/PageSpinLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
